### PR TITLE
convolution fft

### PR DESCRIPTION
**Pull request by andcastillo**

### CODE REVIEW

**Comment by targos** [comment]
Ping @andcastillo. Do you have time to continue this work ?

**Comment by andcastillo** [comment]
Yes, I'll have this Friday. Direct convolution will be the default and FFT will be optional.

**Comment by andcastillo** [comment]
@targos , I've finished the convolution function. I've added the test cases for the direct and fft convolution. The direct convolution is the default. Perhaps in the future, the memory use of the fft can be reduced and we can change to fft by default. For small filters (< 9 rows and <9 columns) the direct is faster than the fft. If the filter is bigger than 17 rows(and columns), there is an important saving of time with the fft. Nevetherless, it can only deal with images of less than 3K  for fft but 6K for direct convolution.

On local,   1) save to disk load then save (jpg)  test is failing. But it is failing even in the master branch, so it is not related with the changes I've introduced in the convolution.
```
  1) save to disk load then save (jpg)
      canvas[method] is not a function
     at node_modules/canvas/lib/jpegstream.js:44:19

```

**Comment by lpatiny** [comment]
@andcastillo Sorry for this late answer. Indeed the test are passing perfectly here. It is always a little bit more difficult to let it run on a Mac ... and impossible to let it run on a Windows computer ;)

**Comment by targos** [comment]
I still wanted to review the changes...

**Pull request merged**
